### ISSUE TITLE
Make toolbox multi user

### ISSUE THREAD

**Issue by EthraZa** [flatcar-linux/toolbox#4]
When I try to open another terminal, it shows **Directory tree /var/lib/toolbox/sailor-ethraza_backops-latest is currently busy**.
As you can see, I tryed to set **--ephemeral** flag but it didn't work at all.

Is it possible to get toolbox to work for multiple logins?

$ cat /etc/lsb-release
```
DISTRIB_ID="Flatcar Container Linux by Kinvolk"
DISTRIB_RELEASE=2512.4.0
DISTRIB_CODENAME="Oklo"
DISTRIB_DESCRIPTION="Flatcar Container Linux by Kinvolk 2512.4.0 (Oklo)"
```

$ cat /home/sailor/.toolboxrc
```
TOOLBOX_DOCKER_IMAGE=ethraza/backops
TOOLBOX_USER=sailor
TOOLBOX_FLAGS="--system-call-filter=bpf --ephemeral"
TOOLBOX_BIND="--bind=/:/media/root --bind=/usr:/media/root/usr --bind=/run:/media/root/run --bind=/sys/fs/bpf:/sys/fs/bpf --bind=/var/run/docker.sock:/var/run/docker.sock --bind=/var/backops/home/sailor:/home/sailor --bind=/mnt/storage:/mnt/storage --bind=/tmp:/tmp"
```

$ ssh -C sailor@kirk
```
Last login: Mon Sep 14 15:43:13 2020 from 187.3.21.98
Flatcar Container Linux by Kinvolk stable (2512.4.0)
Directory tree /var/lib/toolbox/sailor-ethraza_backops-latest is currently busy.
Connection to kirk closed.
```

**Comment by pothos** [comment]
Hi,

yes, that's a problem with the current implementation. A workaround is documented here:
https://docs.flatcar-linux.org/os/install-debugging-tools/#spawn-a-toolbox-with-tmux-in-the-background

**Comment by EthraZa** [comment]
Hi, thanks for answering.

I had to change the host sailor shell from /usr/bin/toolbox back to /bin/bash to be able to login to it in the host shell and execute the systemd-run command. 
But after I managed to get it running (sudoing tmux and strace inside the container), I saw that every nsenter would get the same session, not a new one. Maybe I'm missing something, not sure.

**Comment by pothos** [comment]
Correct, with `nsenter` the namespace of the current `tmux` process is entered and with `tmux a` it attaches to the session. You can change it to run multiple tmux sessions and create new ones. Without the `a` you create a new tmux session but when you have multiple sessions you need to give them a name and attach to this name or otherwise end up looking for PIDs and trying each.

**Comment by EthraZa** [comment]
I see.

Well, in the mean time, I learned that run the same image with docker using **pid:host**, will give me what I want while keeping the multi user possible.

I will let the toolbox/rkt asleep for the day docker will not run for some reason, till there, I will keep to docker.

Thank you.
